spring:
    datasource:
        driverClassName: org.h2.Driver
        username: sa
        password:
        url: jdbc:h2:file:/opt/jpadb1
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect